### ISSUE TITLE
Install needed too much ressources

### ISSUE THREAD

**Issue by kidonsky** [YunoHost-Apps/vaultwarden_ynh#114]
### Description

Installation of Bitwarden app took a lot of time, and... Nothing. No more ssh, no more web access but ping was OK.
Twenty minutes after the blackout begin, all accesses were back and I understood this state from logs:
**From ynh logs**
- Install failed 
- remove_on_failed_install failed too
**From dmesg**
- Too much ressources taken by yunohost, system killed yunohost

### Context

- Hardware: VPS bought online -- 2Go RAM
- YunoHost version: 4.1.7.1
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: trying to install bitwarden app without tweaks

### Steps to reproduce

Install from web admin.
I'm afraid that if I retry from CLI it will give same result with a blackout from my instance

### Expected behavior

Easy install like usual.

### Logs

- Install failed short-version https://paste.yunohost.org/qecefucavu.vbs
- Install failed long-version https://paste.yunohost.org/raw/pabixaxete
- Remove on failed install failed https://paste.yunohost.org/raw/ohixizebes
- Dmseg log full of this type of log https://paste.yunohost.org/wejucijeku.sql

---

### Comment

Why this app needs so much compilation ? Is it a such particular case ?

### The end

Thank you very much for your time and help !

**Comment by yalh76** [comment]
Upstream app needs to compile using rust source code for install and upgrade. So, until upstream app provide already built release, no choice....
