### ISSUE TITLE
The install stops before the end

### ISSUE THREAD

**Issue by damienbesson** [YunoHost-Apps/vaultwarden_ynh#143]
### Describe the bug

First, many thank for all your work ! :)

I have tried to install vaultwarden several times, without success. It's a first install, not a migration from bitwarden.
During the installation (whether using webadmin or ssh command line) the script runs without any particular problems. During the compilation phase, everything goes fine until it suddenly stops (not depending on the package compiling). At the same time, I lose the connection with my machine, and all services restart. After that, Vaultwarden does show up as an installed app, but when I try to access it I get a 502 error...

It looks like a timeout, but I'm still looking for the component !

### Context

- Hardware: Old laptop or computer with 8GB RAM
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH or through the webadmin 
- I'm trying to install package version/branch: stable

### Steps to reproduce

    ```sh
    sudo yunohost app install vaultwarden
    ```

### Logs

https://paste.yunohost.org/raw/ulexicewix

Thanks for your help

**Comment by yalh76** [comment]
Could you try to install with screen like for Mastodon https://github.com/YunoHost-Apps/mastodon_ynh#using-screen-in-case-of-disconnect

Building that app is huge :/

**Comment by damienbesson** [comment]
Thanks for the guess. I tested but without success. With SSH, I lose connection, and when I reconnect and try to restart the screen with `screen -r` it tells me that there is no screen to resume :(
This time, the install stops here : https://paste.yunohost.org/raw/zediqorofa

**Comment by yalh76** [comment]
well, then you should try install directly from the laptop, instead on launching the command remotly...

**Comment by damienbesson** [comment]
well, thanks for your help, it seems to work !
