### ISSUE TITLE
Cannot setup the SMTP

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/vaultwarden_ynh#145]
### Describe the bug

I am trying to setup the SMTP but am getting this error:
```
SMTP 5xx error: lettre::transport::smtp::Error { kind: Permanent(Code { severity: PermanentNegativeCompletion, category: Unspecified3, detail: Five }) }
```
As far as I know I have added the credentials correctly.

### Context

- Hardware: *VPS bought online
- YunoHost version: 4.2.6.1 (stable)
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

**Comment by yalh76** [comment]
where do this log comes from ?

**Comment by tio-trom** [comment]
It was from the admin panel when I was trying to setup the email. I have gave up to this service since then because it was too much for me to setup and handle, so I will close this issue for now. Thank you for your reply!

**Comment by anmol26s** [comment]
This is a known problem in the latest version. This should not be closed.
