### ISSUE TITLE
Error on install - probably because "subslice patterns are unstable"

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/vaultwarden_ynh#146]
**How to post a meaningful bug report**

### Describe the bug
Hi everybody,

I'm trying to install vaultwarden (after uninstalling bitwarden) on my local machine. But it always aborts with an error - please see the logs [here](https://paste.yunohost.org/raw/asaroxepaz)

I'm not that good in understanding logs, but I think it is not running out of RAM because I do have 16GB and not that much running on that machine.

I found something related to rust, the error says something about "subslice patterns are unstable".

There is an open issue related to that at the rust repo:
https://github.com/immunant/c2rust/issues/323

I'm just a noop trying to provide as much information as possible. Looking forward for some help

Thanks in advance
NR

**Comment by croulibri** [comment]
Hello,
I am facing the same issue for a month and a half when trying to install Vaultwarden (https://github.com/YunoHost-Apps/vaultwarden_ynh/issues/137#issuecomment-856229766). I have also quite a lot of RAM, so it should not prevent the install (RAM: Total: 1,9 GB - SWAP: Total: 4,5 GB).
... And I am also unable to install Vaultwarden :-(
Hopefully, my old Bitwarden app still works :-)

**Comment by croulibri** [comment]
Hello @nr458h and @imacfan ,
Have you seen any progress on our shared issue?
I can't test again on my Yunohost as I need an operational Bitwarden for my passwords (I couldn't migrate to Vaultwarden so far).
Have you tried the migration tool to move from Bitwarden to Vaultwarden?

**Comment by imacfan** [comment]
> Hello @nr458h and @imacfan ,
> 
> Have you seen any progress on our shared issue?
> 
> I can't test again on my Yunohost as I need an operational Bitwarden for my passwords (I couldn't migrate to Vaultwarden so far).
> 
> Have you tried the migration tool to move from Bitwarden to Vaultwarden?

I was able to install it. Had to keep it running it long enough. Could not figure out what the issue was.

**Comment by croulibri** [comment]
Good news!
But I understand you have not been using the migration tool.
You have uninstalled Bitwarden and installed a fresh Vaultwarden, haven't you ?

**Comment by imacfan** [comment]
> Good news!
> 
> But I understand you have not been using the migration tool.
> 
> You have uninstalled Bitwarden and installed a fresh Vaultwarden, haven't you ?

Yup, it was a fresh install
