### ISSUE TITLE
Installation on domain root doesn't work

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/vaultwarden_ynh#157]
I changed the app domain to work around #142 . I "moved" vaultwarden on vault.mydomain.fr.

When trying to access the app, Firefox was angry : webpage is incorrectly redirected.
In fact, the web page was redirecting to itself, thus creating an infinite redirect loop.
Probably an issue in nginx ?

Workaround: I moved vaultwarden to vault.mydomain.fr/vaultwarden and redirected the domain root to it.

**Comment by yalh76** [comment]
Can you provide the yunopaste fo the change_url you made on vaultwarden ?

**Comment by Salamandar** [comment]
I'm sorry I may have cleaned up my logs :(
