### ISSUE TITLE
No installed app list in ynh webadmin after upgrade

### ISSUE THREAD

**Issue by MarinLGU** [YunoHost-Apps/vaultwarden_ynh#158]
Hello,
I just realized the upgrade from Bitwarden_RS to this vaultwarden repo following the Readme. Everything went fine apart from yunohost webadmin perspective where there are no app displayed anymore. I think this is the exact same story as described here : https://forum.yunohost.org/t/plus-aucune-app-installees-en-partie-admin as I have the same error logs in my browser's debug console. Is there a fix about this problem ?
Thanks a lot,
Marin

**Comment by yalh76** [comment]
Hi, 

Do you have other apps installed on you YunoHost Server ? Can you see them in the webadmin ?

**Comment by MarinLGU** [comment]
Hi, 
Yes I have many others, and I can't see them in the webadmin either,
Thanks,
Marin

**Comment by niemanna** [comment]
Same here, additionally i get the warning that the bitwarden app is not in the catalog anymore, although i have upgraded to vaultwarden, reinstalled vaultwarden afterwards and removed the upgraded instance (with the bitwarden URL)

**Comment by MarinLGU** [comment]
If I may add some information, when I execute `yunohost app list` in the command line, I still get two outputs for the "same" app : 
`apps:                                                                                                                                                                                                              
  0:                                                                                                                                                                                                               
    description: Manage passwords and other sensitive informations                                                                                                                                                 
    domain_path: pwd.le-guillou.dev/                                                                                                                                                                               
    id: bitwarden                                                                                                                                                                                                  
    name: Vaultwarden                                                                                                                                                                                              
    version: 1.22.2~ynh1`
and 
`10:
    description: Manage passwords and other sensitive informations
    domain_path: pwd.le-guillou.dev/
    id: vaultwarden
    name: Vaultwarden
    version: 1.22.2~ynh1`
By the way, on my last backup report I get error for bitwarden and sucess for vaultwarden.

**Comment by MarinLGU** [comment]
If I may add some information, when I execute yunohost app list in the command line, I still get two outputs for the "same" app :
`apps:0: description: Manage passwords and other sensitive informations domain_path: ****.domain/ id: bitwarden name: Vaultwarden version: 1.22.2~ynh1` 
and
`10: description: Manage passwords and other sensitive informations domain_path: ****.domain/ id: vaultwarden name: Vaultwarden version: 1.22.2~ynh1` 
By the way, on my last backup report I get error for bitwarden and sucess for vaultwarden.

**Comment by niemanna** [comment]
Exactly same here! Even if i have deinstalled the former bitwarden instance it is still in the applist

**Comment by ColinMaudry** [comment]
Same here: upgrading Bitwarden has hidden all other apps, they seem to work, but Bitwarden (vaultwarden) doesn't work. Both bitwarden and vaultwarden appear in `yunohost app list`, but not in admin.

**Comment by ColinMaudry** [comment]
I have tried to install the version of Bitwarden I was using previously ([here](https://github.com/YunoHost-Apps/vaultwarden_ynh/commit/36afe70c2fa62f6cdc6290cdbbceabfc64542984)), it failed: https://paste.yunohost.org/raw/lepekixiko

**Comment by MarinLGU** [comment]
Ok, on my side I got everything back when removing the app with id "bitwarden" (as opposed to the new one with id "vaultwarden", even if both names were "Vaultwarden") from command line.

**Comment by ColinMaudry** [comment]
@MarinLGU What command did run exactly? Thanks.

**Comment by MarinLGU** [comment]
`sudo yunohost app remove bitwarden`

**Comment by ColinMaudry** [comment]
Yup, the list of apps is back indeed, thanks :)
