### ISSUE TITLE
Failed update bitwarden to vaultwarden

### ISSUE THREAD

**Issue by devinberg** [YunoHost-Apps/vaultwarden_ynh#166]
### Context

- Hardware: *VPS bought online*
- YunoHost version: *4.3.5*
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *1.23.0~ynh2*
- If upgrading, current package version: *1.19.0~ynh1*

### Steps to reproduce

Attempted to upgrade via the provided command:
`sudo yunohost app upgrade bitwarden -u https://github.com/YunoHost-Apps/vaultwarden_ynh --debug`

### Expected behavior

Upgrade successfully.

### Logs

[Log output](https://paste.yunohost.org/raw/oyipazuweh)

**Comment by devinberg** [comment]
I just tried updating again after you merged this fix, but it failed again. https://paste.yunohost.org/raw/eturazotor

Is this because I had a previous failure or is the same issue persisting?

**Comment by Tagadda** [comment]
This is due to the previous failure, the migration script did not end properly last time.
Here, this is the backup could not find `/var/www/bitwarden` because it has been renamed to `vaultwarden`.

You can skpi the backup with `-b` but I'm not sure this will work either.

Maybe you should restore the bitwarden backup from before your first attempt and then run the upgrade.

**Comment by devinberg** [comment]
@Tagadda Ok, so I tried deleting bitwarden and restoring from the backup. That also failed. Then I removed bitwarden/vaultwarden again and tried installing Vaultwarden as normal. The install succeeded, but now I am still getting the `502 Bad Gateway`.

I tried: `root@apps:/var/www/vaultwarden/live# cp -a vaultwarden.env .env` as was shown in #164, but that didn't fix the issue.

` tail -10 /var/log/daemon.log`

produces:
```
Jan 28 15:06:17 apps vaultwarden[4857]: |--------------------------------------------------------------------|
Jan 28 15:06:17 apps vaultwarden[4857]: | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
Jan 28 15:06:17 apps vaultwarden[4857]: | official channels to report bugs/features, regardless of client.   |
Jan 28 15:06:17 apps vaultwarden[4857]: | Send usage/configuration questions or feature requests to:         |
Jan 28 15:06:17 apps vaultwarden[4857]: |   https://vaultwarden.discourse.group/                             |
Jan 28 15:06:17 apps vaultwarden[4857]: | Report suspected bugs/issues in the software itself at:            |
Jan 28 15:06:17 apps vaultwarden[4857]: |   https://github.com/dani-garcia/vaultwarden/issues/new            |
Jan 28 15:06:17 apps vaultwarden[4857]: \--------------------------------------------------------------------/
Jan 28 15:06:17 apps systemd[1]: vaultwarden.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 15:06:17 apps systemd[1]: vaultwarden.service: Failed with result 'exit-code'.
```

Is there something else I can try?

**Comment by Tagadda** [comment]
I would try to run vaultwarden manually, it should give more logs this way.
Something like this : 
`sudo -u vaultwarden /var/www/vaultwarden/live/vaultwarden`
I would check the service configuration at `/etc/systemd/system/vaultwarden.service` and permissions for `/home/yunohost.app/vaultwarden/`.

**Comment by devinberg** [comment]
Is `vaultwarden.service` missing the `__DATA__` location?
```
[Unit]
Description=vaultwarden Server (Rust Edition)
Documentation=https://github.com/dani-garcia/vaultwarden
After=network.target

[Service]
# The user/group vaultwarden is run under. the working directory (see below) should allow write and read access to this user/group
User=vaultwarden
Group=vaultwarden
WorkingDirectory=/var/www/vaultwarden/live/
ReadWriteDirectories=/var/www/vaultwarden/live/
EnvironmentFile=/var/www/vaultwarden/live/vaultwarden.env
ExecStart=/var/www/vaultwarden/live/vaultwarden

# Set reasonable connection and process limits
LimitNOFILE=1048576
LimitNPROC=64

# Sandboxing options to harden security
# Depending on specificities of your service/app, you may need to tweak these
# .. but this should be a good baseline
# Details for these options: https://www.freedesktop.org/software/systemd/man/systemd.exec.html
PrivateTmp=yes
PrivateDevices=yes
ProtectHome=true
ProtectSystem=strict

[Install]
WantedBy=multi-user.target
```

**Comment by Tagadda** [comment]
This is not the last version, `ProtectHome` should be false too...
Try this `sudo yunohost upgrade vaultwarden -u https://github.com/YunoHost-Apps/vaultwarden_ynh/tree/master -f -b`

**Comment by devinberg** [comment]
Yay! That worked! Slight modification to your command, but after the forced upgrade, it is loading again. Thanks for your help!

`sudo yunohost app upgrade vaultwarden -u https://github.com/YunoHost-Apps/vaultwarden_ynh/tree/master -F -b`

**Comment by 4abhinavjain** [comment]
> Yay! That worked! Slight modification to your command, but after the forced upgrade, it is loading again. Thanks for your help!
> 
> `sudo yunohost app upgrade vaultwarden -u https://github.com/YunoHost-Apps/vaultwarden_ynh/tree/master -F -b`

@devinberg for me, the command above also resolved 502 error I was getting: https://github.com/YunoHost-Apps/vaultwarden_ynh/issues/164#issuecomment-1019463472
