### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Jinux-1** [YunoHost-Apps/vaultwarden_ynh#168]
**502 Bad Gateway**
Bug happened after upgrading to latest testing branch today (24/01/22)
Current version is 1.23.0~ynh2
Vaultwarden is installed on bw.[mydomain].com instead of [mydomain].com/vaultwarden or bw.[mydomain].com/vaultwarden
Trying to navigate anywhere on vaultwarden subdomain leads to this error

### Context

- Hardware: Dell Optiplex in-home hosted
- YunoHost version: 4.3.6.2 (stable)
- I have access to my server: All methods
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: Testing branch for vaultwarden
- Using, or trying to install package version/branch: testing
- If upgrading, current package version: 1.23.0~ynh2
### Steps to reproduce
1. Upgrade to latest testing branch
2. Visit vaultwarden
3. 502 Bad Gateway error

### Expected behavior
View the web vault

### Logs
https://paste.yunohost.org/raw/kadefaqeli

**Comment by yalh76** [comment]
similar as #164 164
