### ISSUE TITLE
Upgrade issue - 1.24.0~ynh1 to 1.25.0~ynh1

### ISSUE THREAD

**Issue by imacfan** [YunoHost-Apps/vaultwarden_ynh#188]
- Hardware: *Raspberry Pi at home *
- YunoHost version: 4.3.6.3 (stable).
- I have access to my server: *Through through the webadmin | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no *

### Steps to reproduce
upgrading Vaultwarden (vaultwarden) from 1.24.0~ynh1 to 1.25.0~ynh1
   
### Expected behavior

Was expecting upgrade but it stops in between. tried few times but same issue appeared. Please check log 
### Logs

https://paste.yunohost.org/raw/asedefizut

**Comment by yalh76** [comment]
L1279
`2022-06-04 11:57:07,470: DEBUG - error: couldn't create a temp dir: No space left on device (os error 28) at path "/var/www/vaultwarden/build/target/release/deps/rmetaQclrqW"`

No space left on device

**Comment by imacfan** [comment]
there is lot of space on device... I had similar issue in past as well. Something to do with swap memory. which got fixed in later version. Seems it got reintroduced again

**Comment by yalh76** [comment]
As you can see, there is no modification around swap in https://github.com/YunoHost-Apps/vaultwarden_ynh/pull/187/files

**Comment by imacfan** [comment]
How much space does it need? I have 7.3GB available

**Comment by yalh76** [comment]
After some tests, it seems that the upgrade require 4GB

**Comment by centralscrutinizer21** [comment]
indeed serting swap file to 4 gb did the trick.

**Comment by imacfan** [comment]
Fixed after creating space in the drive.
