### ISSUE TITLE
Upgrade fails - Vaultwarden (vaultwarden) from 1.22.2~ynh1 to 1.25.0~ynh1

### ISSUE THREAD

**Issue by razzor1984** [YunoHost-Apps/vaultwarden_ynh#189]
### Describe the bug

Update fails  Error: "504" Gateway Timeout

### Context

- Hardware: *RPI 3b+*
- YunoHost version: 4.3.6.3 (stable)
- I have access to my server: through the webadmin  * yes*
- Using, or trying to install package version/branch: *vaultwarden*
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $vaultwarden

### Steps to reproduce

- *If you used the webadmin, please perform the equivalent command from the CLI first.*
 Just triggert the update in the Webgui to version 1.25.0 (vaultwarden)
)
### Expected behavior

an successful upgrade to 1.25.0 (vaultwarden)

### Logs

 Upgrade 'vaultwarden' app
25
YunoHost encountered an unexpected error
Really sorry about that.
You should look for help on the forum or the chat to fix the situation, or report the bug on the bugtracker.
The following information might be useful for the person helping you:

Error: "504" Gateway Timeout

Action: "PUT" /yunohost/api/apps/vaultwarden/upgrade

Error message:

504 Gateway Time-out
nginx

```
While processing the action the server said:
Now upgrading vaultwarden...
Loading installation settings...
Checking version...
Backing up the app before upgrading (may take a while)...
Stopping a systemd service...
(this may take some time)
The service vaultwarden didn't fully executed the action stop before the timeout.
Please find here an extract of the end of the log of the service vaultwarden:
Jun 11 19:49:50 systemd[1]: Stopping vaultwarden Server (Rust Edition)...
Jun 11 19:49:50 systemd[1]: vaultwarden.service: Main process exited, code=killed, status=15/TERM
Jun 11 19:49:50 systemd[1]: vaultwarden.service: Succeeded.
Jun 11 19:49:50 systemd[1]: Stopped vaultwarden Server (Rust Edition).
Ensuring downward compatibility...
Making sure dedicated system user exists...
Making sure data directory exists...
Upgrading source files...
Upgrading NGINX web server configuration...
Upgrading dependencies...
Making upgrade...
info: downloading installer
info: profile set to 'default'
info: default host triple is armv7-unknown-linux-gnueabihf
info: syncing channel updates for 'nightly-armv7-unknown-linux-gnueabihf'
info: latest update on 2022-06-11, rust version 1.63.0-nightly (ec55c6130 2022-06-10)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
info: default toolchain set to 'nightly-armv7-unknown-linux-gnueabihf'

```

**Comment by yalh76** [comment]
can you provide the full upgrade log in a yunopaste
