### ISSUE TITLE
Upgrade failed - 1.24.0~ynh1 to 1.25.0~ynh1

### ISSUE THREAD

**Issue by devinberg** [YunoHost-Apps/vaultwarden_ynh#190]
### Describe the bug

Receiving ``` DEBUG - error: could not compile `vaultwarden` ``` when attempting upgrade from 1.24.0 to 1.25.0.

### Context

- Hardware: VPS
- YunoHost version: 4.3.6.3
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 1.25.0
- If upgrading, current package version: 1.24.0

### Logs

https://paste.yunohost.org/raw/kejaruhate

**Comment by curious-jeremy** [comment]
Exact same context and issue here. The logs are similar.

**Comment by curious-jeremy** [comment]
Looks like it is a memory shortage issue when building the app. Performing the upgrade via the command line worked around the problem for me.

**Comment by devinberg** [comment]
Yea, I did try via CLI also and got the same error. https://paste.yunohost.org/raw/nofemudadi

**Comment by fthouvenin** [comment]
Same problem as @devinberg (via cli or web). In the meantime I upgrade to YNH 11 but same : https://paste.yunohost.org/raw/usopanosil
