### ISSUE TITLE
Upgrade failed -  rustc 1.49 or newer is required

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/vaultwarden_ynh#200]
### Describe the bug

error: package `tokio v1.20.0` cannot be built because it requires rustc 1.49 or newer, while the currently active rustc version is 1.41.1

### Context

- Hardware: odroid hc1 armhf(v7) 2Gb RAM
- YunoHost version: 4.3.6.3
  -  I have access to my server: Through SSH | through the webadmin
  - Are you in a special : yes inside lxc container
- version/branch: master
- If upgrading, current package version: 1.24.0~ynh1 to 1.25.2~ynh1

### Steps to reproduce

uprade from WEBUI or CLI

### Expected behavior

Upgrade works

### Logs
```
$ apt search rustc
rustc/oldstable,now 1.41.1+dfsg1-1~deb10u1 armhf [installed]
  Rust systems programming language

rustc-mozilla/oldstable 1.51.0+dfsg1-1~deb10u2 armhf
  Rust systems programming language
```

logs
**https://paste.yunohost.org/raw/jupicefaxe**

**Comment by yalh76** [comment]
thanks for the report, it seems specific to armhf, I've updated the way rustup is installed in #201, we will see if it works
