### ISSUE TITLE
Reinstalling VaultWarden -> Admin Token error

### ISSUE THREAD

**Issue by rob-hills** [YunoHost-Apps/vaultwarden_ynh#206]
### Describe the bug

When you install VaultWarden it triggers an automated email to the administrator containing an Admin Token.  If you ***uninstall*** VaultWarden and ***reinstall it again***, it sends a new automated email with a new Admin Token, but the new token *doesn't work*.  

You need to use the ***original Admin Token generated by the first installation*** to be able to log in successfully.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.0.9.11
- I have access to my server: *Through SSH and the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *1.25.2~ynh2*

I originally installed VaultWarden using my own personal YunoHost login as the VaultWarden Administrator but then discovered that this then prevented me from creating my own VaultWarden account using the same email :-(

So, I uninstalled VaultWarden, created a VaultWarden Admin user in YunoHost and then reinstalled VaultWarden using my new VaultWarden Admin user.

### Steps to reproduce
 - Install VaultWarden via the Webadmin interface
 - Receive the admin email containing the Admin Token and retain
 - Log in to the VaultWarden Admin interface using the token (may or may not be a required step, but I did this)
 - Uninstall VaultWarden via the Webadmin interface
 - Install VaultWarden again via the Webadmin interface
 - Receive the new admin email containing a new Admin Token
 - Try to log in using the new admin token -> "Error, invalid Admin Token, please try again"
 - Try to log in using the original Admin Token from the first installation -> successful login.

### Expected behavior

I expected VaultWarden to permit login using the Admin Token sent after the second installation and ***not*** permit login using the original Admin Token from the first installation.

### Logs
I couldn't see anything relevant in the installation log but I can provide the installation log for the second installation if required.

**Comment by yalh76** [comment]
That's because the database containing the masterkey is stored appart in `/home/yunohost.app/vaultwarden`.

When reinstalling, it uses the already existing database.

If you want to have a new masterkey, you should remove vaultwarden purging the datadir: `yunohost app remove vaultwarden --purge`
