### ISSUE TITLE
Upgrade to 1.26.0~ynh1 fails.

### ISSUE THREAD

**Issue by mtenders** [YunoHost-Apps/vaultwarden_ynh#217]
### Describe the bug

I was unable to upgrade from `1.25.2~ynh4` to `1.26.0~ynh1`.

### Context

- Hardware: Raspberry Pi 4B
- YunoHost version: 11.0.10.1
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 1.26.0~ynh1
- If upgrading, current package version: 1.25.2~ynh4

### Steps to reproduce

- Upgrade the app
    ```sh
    sudo yunohost app upgrade vaultwarden
    ```

### Logs
https://paste.yunohost.org/raw/mekemeduzu

**Comment by yalh76** [comment]
Can you try to upgrade from ssh command line doing `yunohost app upgrade vaultwarden --url https://github.com/YunoHost-Apps/vaultwarden_ynh/tree/arm --force`

**Comment by mtenders** [comment]
Removing the quotes around the `os_arch_variant` value solved the problem for me. (#219) Thanks!
