### ISSUE TITLE
Vaultwarden 404 when installed on pw.example.org instead of pw.example.org/vaultwarden

### ISSUE THREAD

**Issue by utzer** [YunoHost-Apps/vaultwarden_ynh#231]
### Describe the bug

Vaultwarden 404 when installed on pw.example.org instead of pw.example.org/vaultwarden because of “Enable the small ‘YunoHost’ portal shortcut square on apps”. 
When “Enable the small ‘YunoHost’ portal shortcut square on apps” is disabled it still gives 404, but less faults in the Firefox console. 

For details please see the related post in the [Yunohost forum](https://forum.yunohost.org/t/vaultwarden-404-when-installed-in-pw-example-org-instead-of-pw-example-org-vaultwarden/24479/4). 

### Context

- Hardware: Rented server, not VPS but hardware. 
- YunoHost version: YunoHost 11.1.18 (stable)
- I have access to my server: Through SSH & through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain: -
- Using, or trying to install package version/branch: 1.28.1~ynh1
- If upgrading, current package version: -

### Steps to reproduce

- Setup a domain, ie. pw.example.org. 
- Install Vaultwarden via CLI or webadmin, select to use pw.example.org/ as domain. 
- See the faults happening, more vaults when “Enable the small ‘YunoHost’ portal shortcut square on apps” is active. 

Alternative that works. 
- Setup a domain, ie. pw.example.org. 
- Install Vaultwarden via CLI or webadmin, select to use pw.example.org/vaultwarden as domain. 
- It should work
(I write should, because it worked a week before until I wanted to switch from pw.example.org/vaultwarden to pw.example.org/ and in the course uninstalled Vaultwarden and now neither works, but the pw.example.org/vaultwarden throws alot of faults in Firefox console.)

Faults for pw.example.org/ with “Enable the small ‘YunoHost’ portal shortcut square on apps” active:
```
ynh_portal.js:1     Failed to load resource: the server responded with a status of 403 ()
pw.example.org/:1 Refused to execute script from 'https://pw.example.org/ynh_portal.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
pw.example.org/:1 Refused to apply style from 'https://pw.example.org/ynh_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
custom_portal.js:1     Failed to load resource: the server responded with a status of 403 ()
pw.example.org/:1 Refused to execute script from 'https://pw.example.org/ynhtheme/custom_portal.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
pw.example.org/:1 Refused to apply style from 'https://pw.example.org/ynhtheme/custom_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
/favicon.ico:1     Failed to load resource: the server responded with a status of 404 ()
pw.example.org/:1 Refused to apply style from 'https://pw.example.org/ynh_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
pw.example.org/:1 Refused to apply style from 'https://pw.example.org/ynhtheme/custom_overlay.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

Faults for pw.example.org/ with “Enable the small ‘YunoHost’ portal shortcut square on apps” **NOT** active:
`/favicon.ico:1     Failed to load resource: the server responded with a status of 404 ()`

Tried to put a favicon.ico in /var/www/vaultwarden/favicon.ico, but that leaves me with:
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
pw.example.org/:1     GET https://pw.example.org/ 404
```
Journalctl:
```
Apr 21 11:31:03 vaultwarden[1275855]: [2023-04-21 11:31:03.694][rocket::server::_][ERROR] No matching routes for GET / text/html.
Apr 21 11:31:03 vaultwarden[1275855]: [2023-04-21 11:31:03.694][rocket::server::_][WARN] No 404 catcher registered. Using Rocket default.
```

/var/log/vaultwarden/vaultwarden.log:
```
[2023-04-21 11:31:03.694][rocket::server::_][ERROR] No matching routes for GET / text/html.
[2023-04-21 11:31:03.694][rocket::server::_][WARN] No 404 catcher registered. Using Rocket default.
```

### Expected behavior

Vaultwarden loads and does not 404. 

### Logs

I can provide whatever log you like, but surely the Journalctl and vaultwarden.log do not contain anything helpful, I think there is a wrong setup of the webserver during the installation, it should catch the favicon.ico call and it should catch the requests regarding the shortcut square, so I guess someone has to fix that, I would be very happy to help and provide the information needed.

**Comment by utzer** [comment]
Which information can I add here to help solve this bug?

**Comment by utzer** [comment]
Is there anyone here reading these issues and is this Yunohost Application still maintained?

**Comment by utzer** [comment]
Nothing?

**Comment by eldertek** [comment]
Same for me

**Comment by Tagadda** [comment]
I'm not able to reproduce this issue nowadays.
