### ISSUE TITLE
Upgrade to 1.30.1

### ISSUE THREAD

**Issue by Quiwy** [YunoHost-Apps/vaultwarden_ynh#253]
Version [1.30.1 is out since mid november](https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.1).
It would be great to see the update landing in yunohost 😄 .

**Comment by ericgaspar** [comment]
Thanks for the reminder. This is already on track (but failing tests) #244

**Comment by Quiwy** [comment]
Oups sorry, I checked on the issues side but not on the MR side 😅

**Comment by vanyasem** [comment]
1.30.3 is out https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.3
