### ISSUE TITLE
Add pre-compiled builds for ARM/RPi

### ISSUE THREAD

**Issue by alon7786** [YunoHost-Apps/vaultwarden_ynh#95]
Hi,

I couldn't upgrade to 1.16 from 1.15.
After a lot of failed attempts, I saved the configuration and exported the data, I uninstalled the app with hope that clean install will resolve the issue.
The issue was that the RPi just hang at various compilation modules.

After a lot of debugging I found that the compilation killing my Pi, with the following command I found out that my Pi throttles hangs, temps jumps over 85C and under-voltage (only on select modules).
`watch -n 1 "vcgencmd measure_clock arm; vcgencmd measure_temp; vcgencmd get_throttled"`
    0: under-voltage
    1: arm frequency capped
    2: currently throttled
    16: under-voltage has occurred
    17: arm frequency capped has occurred
    18: throttling has occurred

Since the day-to-day usage of my pi is YunoHost with Bitwarden the 2.1amp charger is more than enough, so to overcame this issue, I can pre-compile on other PC the binaries, or add compiled binaries to the ynh app will be perfect.

**Comment by yalh76** [comment]
would be better to help upstream app https://github.com/dani-garcia/bitwarden_rs to provide already built release ^^

**Comment by OniriCorpe** [comment]
may this be usefull? https://github.com/dani-garcia/vaultwarden/wiki/Pre-built-binaries
